name: Generate new graph

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '40 * * * *'
      
jobs:
  build:
    runs-on: macOS-latest
    env:
      DEVTO: ${{ secrets.DEVTO }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('DaveParr/dev.to.ol')"
          Rscript -e "install.packages('gh')"
          Rscript -e "install.packages('tibble')"
          Rscript -e "install.packages('tidyr')"
          Rscript -e "install.packages('dplyr')"
          Rscript -e "install.packages('ggplot2')"
          Rscript -e "install.packages('stringr')"
      - name: Run repos
        run: |-
          Rscript -e "source('repos.R')"
      - name: Run blogs
        run: |-
          Rscript -e "source('blogs.R')"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add graph.png
          git commit -m "Update the graph" -a || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
          