# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.Rmd']
  scehdule:
    - cron: '25 16 * * *'

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DEVTO: ${{ secrets.DEVTO }}
    steps:
      - name: Install libcurl
        run: >
          sudo apt-get update && sudo apt-get install --yes
          libcurl4-openssl-dev

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: '4.1.2'

      - uses: r-lib/actions/setup-renv@v2

      - name: Render readme
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit rendered files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          # add files in README_files directory
          git add graph.png
          git status
          git commit -m "Update the README" -a || echo "No changes to commit"
          git status
          git push origin || echo "No changes to commit"
          
